# Jekyll configuration for iSBatch Page

name: iSBatch
description: Hyearchical Data Processing Plugin for ImageJ

# url is currently only used only for the RSS feed in feed.xml
url: http://singlemolecule.github.io

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: /iSBatch

# This can be '' to hide the Github nav button
github: 'singlemolecule/iSBatch'

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: 'UA-61088151-3'

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: 'isbatch'
comments: true

gems:
  - jekyll-paginate
  
#permalink: /:year/:month/:title
paginate: 3
paginate_path: "/blog/page:num/"

highlighter: pygments
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

exclude: ['README.md', 'LICENSE']
